### ISSUE TITLE
access Token renewel

### ISSUE THREAD

**Issue by slachtar** [Elyft/Orange-sms#1]
First, thank you for the library.
Just want to ask, is accessToken generated with each sms sending?
If not, do you renew it when expired?
thank you.

**Comment by Elyft** [comment]
Hello Slachtar, sorry for my late response, I was very busy, the token is generated to each message you send.

**Comment by slachtar** [comment]
Thank you for the reply,
well I managed to make the token generated on app startup and when an call get errored due to token having expired, I renew it. I think this is a better than generating a token for each call, especially if you're sending thousands messages a day.
Regards,

**Comment by Elyft** [comment]
you're absolutely right, but the orange developers have made sure that with every call you ask for a new token.
